graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_gptj-99,_pytorch,_cuda,_test,_r5.0-dev_default,_float16,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_gptj-99,_pytorch,_cuda,_test,_r5.0-dev_default,_float16,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_gptj-99,_pytorch,_cuda,_test,_r5.0-dev_default,_float16,_offline_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_gptj-99,_pytorch,_cuda,_test,_r5.0-dev_default,_float16,_offline_) --> get,mlcommons,inference,src
    pull-git-repo,c23132ed65c4421d --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_gptj-99,_pytorch,_cuda,_test,_r5.0-dev_default,_float16,_offline_) --> pull,git,repo
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_reference,_gptj-99,_pytorch,_cuda,_test,_r5.0-dev_default,_float16,_offline_) --> get,mlperf,inference,utils
    get-cuda,46d133d9ef92422d_(_toolkit_) --> detect,os
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,generic-python-lib,_pip
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> detect,cpu
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_pip_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,generic-python-lib,_pip
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_reference,_gptj-99,_pytorch,_cuda,_test,_r5.0-dev_default,_float16,_offline_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,cuda,_cudnn
    get-generic-python-lib,94b62a682bc44791_(_torch_cuda_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,generic-python-lib,_torch_cuda
    get-generic-python-lib,94b62a682bc44791_(_torchvision_cuda_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,generic-python-lib,_torchvision_cuda
    get-generic-python-lib,94b62a682bc44791_(_transformers_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,generic-python-lib,_transformers
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,ml-model,large-language-model,gptj,raw,_pytorch
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,dataset,cnndm,_validation
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93 --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,python
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,mlcommons,inference,src
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93 --> get,sut,configs
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> generate,user-conf,mlperf,inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,loadgen
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_package.datasets_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,generic-python-lib,_package.datasets
    get-generic-python-lib,94b62a682bc44791_(_package.attrs_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,generic-python-lib,_package.attrs
    get-generic-python-lib,94b62a682bc44791_(_package.accelerate_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> get,generic-python-lib,_package.accelerate
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_pytorch,_offline,_gptj-99,_cuda,_float16_) --> benchmark-mlperf